# Generated by Django 5.2.17 on 2026-09-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bankaccounttype_id_alter_user_id_and_more'),
        ('transactions', '0002_alter_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='interest_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('interest_period__isnull', False), ('transaction_type', 3)), fields=('account', 'interest_period'), name='unique_interest_period_per_account'),
        ),
    ]
